name: Pull Request Checks

on:
  workflow_call:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/Hydrogen'
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Build
      run: npm run build
    - name: Cache dist directory
      uses: actions/cache/save@v3
      with:
          path: ./dist/**
          key: ${{ runner.os }}-dist-${{ github.sha }}
