name: Release SNAPSHOT version

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build project
    uses: ./.github/workflows/pr-check.yml
    secrets: inherit
  release-snapshot:
    name: Release SNAPSHOT version
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - build
    steps:
      - name: Restore cached dist directory
        uses: actions/cache/restore@v3
        with:
          path: ./dist/**
          key: ${{ runner.os }}-dist-${{ github.sha }}
          fail-on-cache-miss: true
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish next snapshot
        run: sh ./publish-next-snapshot.sh
      - name: Push changes to main branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'CI: update snapshot version [skip ci]'
          commit_user_name: GitHub Actions
          commit_user_email: github.actions@ds.pl



