name: Release version

on:
  workflow_dispatch:

jobs:
  build:
    name: Build project
    uses: websight-io/websight-localsync/.github/workflows/pr-check.yml@main
  publish:
    name: Remove SNAPSHOT version
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - name: Remove SNAPSHOT version
        run: |
          npm version patch --git-tag-version false
          npm dist-tag rm websight-localsync SNAPSHOT
          rm -rf .npm-snapshot
      - name: Publish if version has been updated
        uses: pascalgn/npm-publish-action@1.3.9
        with:
          commit_pattern: "^CI: prepare release (\\S+) [skip ci]"
          publish_command: "npm"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Prepare for next version
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version-type: 'patch'
          commit-message: 'CI: bump version to {{version}} [skip ci]'
